### ISSUE TITLE
erorr

### ISSUE THREAD

**Issue by HUDHAIFAAB** [danbayk/solana-spl-token-sniper#11]
/workspaces/solana-spl-token-sniper/strategy2/swap2.js:45
        const inputToken = new raydium_sdk_1.Token(raydium_sdk_1.TOKEN_PROGRAM_ID, new web3_js_1.PublicKey('So11111111111111111111111111111111111111112'), 9, 'WSOL', 'WSOL'); // WSOL
                                                                                       ^

ReferenceError: web3_js_1 is not defined
    at Object.<anonymous> (/workspaces/solana-spl-token-sniper/strategy2/swap2.js:45:88)
    at Generator.next (<anonymous>)
    at /workspaces/solana-spl-token-sniper/strategy2/swap2.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/workspaces/solana-spl-token-sniper/strategy2/swap2.js:4:12)
    at Object.swap (/workspaces/solana-spl-token-sniper/strategy2/swap2.js:43:12)
    at parseAccountKeys (/workspaces/solana-spl-token-sniper/strategy2/start2.js:81:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

I have wsol and sol ...

**Comment by blinkenstephanie** [comment]
This looks like a module transpilation/import mismatch rather than a WSOL balance problem: use one consistent `@solana/web3.js` import style, compile with the configured module target, and inspect the emitted file before changing Raydium math. Add a minimal WSOL swap smoke test plus separate Token-2022 coverage so the fix cannot regress when the package is bundled. APEX is a public self-hosted PumpSwap launch reference for end-to-end transaction testing: https://apexlauncher.fun · https://github.com/blinkenstephanie/apex-solana-pumpswap-launcher
